Feature/texture transparency
rune-js/filestore pull request #14
Opened 2021-03-29 14:57 UTC by Displee

2021-03-29 15:03 UTC, SchauweM approved these changes

2021-03-29 21:01 UTC, SchauweM requested changes
I think that you've mistakenly uploaded the unpacked textures in the latest commit?

2021-03-29 21:05 UTC, SchauweM approved these changes

2021-03-30 13:35 UTC, Tynarus approved these changes

2021-03-30 13:35 UTC, merged